# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'flicks' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'AFNetworking', '~> 3.0'
  # Pods for flicks

  target 'flicksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'flicksUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
